server:
    port: 8089


aws:
  region: us-east-2
  secretKey: qKMr4pIWlm6FabEq/ObOU6gKwFsWHScGD7hddSM6
  accessKey: AKIARRQYZMUZTSJAMTYC
  sqs:
    queueName: Payment-sqs

cloud:
  aws:
    region:
      auto: false
      static: us-east-2
    stack: false
    stack.auto: false
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
